### ISSUE TITLE
Screen capture doesn't work in Chromium (negotiation errors from Pipewire)

### ISSUE THREAD

**Issue by Hubro** [hyprwm/xdg-desktop-portal-hyprland#52]
Screen capture works perfectly in OBS and Firefox, but when I try to screen capture in Chrome, Chromium or Vivaldi (so apparently any Chromium based application) then I just get a loading spinner that never resolves.

Meanwhile, Pipewire prints this error:

```
pw.context: params Spa:Enum:ParamId:EnumFormat: 0:0 Invalid argument (input format (no more input formats))
pw.context: Object: size 352, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
pw.context:     Id 2        (Spa:Enum:MediaType:video)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
pw.context:     Id 1        (Spa:Enum:MediaSubtype:raw)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
pw.context:     Id 12       (Spa:Enum:VideoFormat:BGRA)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:modifier (131074), flags 00000018
pw.context:     Choice: type Spa:Enum:Choice:Enum, flags 00000000 88 8
pw.context:       Long 144115188622605059
pw.context:       Long 144115188622605059
pw.context:       Long 144115188622588675
pw.context:       Long 144115188622392067
pw.context:       Long 144115188621122307
pw.context:       Long 144115188084250882
pw.context:       Long 144115188075858177
pw.context:       Long 0
pw.context:       Long 72057594037927935
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000
pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
pw.context:       Rectangle 1x1
pw.context:       Rectangle 1x1
pw.context:       Rectangle -1x-1
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000
pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
pw.context:       Fraction 60/1
pw.context:       Fraction 0/1
pw.context:       Fraction 60/1
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000
pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
pw.context:       Fraction 60/1
pw.context:       Fraction 0/1
pw.context:       Fraction 60/1
pw.context: Object: size 248, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
pw.context:     Id 2        (Spa:Enum:MediaType:video)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
pw.context:     Id 1        (Spa:Enum:MediaSubtype:raw)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
pw.context:     Id 12       (Spa:Enum:VideoFormat:BGRA)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000
pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
pw.context:       Rectangle 1x1
pw.context:       Rectangle 1x1
pw.context:       Rectangle -1x-1
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000
pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
pw.context:       Fraction 60/1
pw.context:       Fraction 0/1
pw.context:       Fraction 60/1
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000
pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
pw.context:       Fraction 60/1
pw.context:       Fraction 0/1
pw.context:       Fraction 60/1
pw.context: Object: size 352, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
pw.context:     Id 2        (Spa:Enum:MediaType:video)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
pw.context:     Id 1        (Spa:Enum:MediaSubtype:raw)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
pw.context:     Id 11       (Spa:Enum:VideoFormat:RGBA)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:modifier (131074), flags 00000018
pw.context:     Choice: type Spa:Enum:Choice:Enum, flags 00000000 88 8
pw.context:       Long 144115188622605059
pw.context:       Long 144115188622605059
pw.context:       Long 144115188622588675
pw.context:       Long 144115188622392067
pw.context:       Long 144115188621122307
pw.context:       Long 144115188084250882
pw.context:       Long 144115188075858177
pw.context:       Long 0
pw.context:       Long 72057594037927935
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000
pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
pw.context:       Rectangle 1x1
pw.context:       Rectangle 1x1
pw.context:       Rectangle -1x-1
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000
pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
pw.context:       Fraction 60/1
pw.context:       Fraction 0/1
pw.context:       Fraction 60/1
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000
pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
pw.context:       Fraction 60/1
pw.context:       Fraction 0/1
pw.context:       Fraction 60/1
pw.context: Object: size 248, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
pw.context:     Id 2        (Spa:Enum:MediaType:video)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
pw.context:     Id 1        (Spa:Enum:MediaSubtype:raw)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
pw.context:     Id 11       (Spa:Enum:VideoFormat:RGBA)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000
pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
pw.context:       Rectangle 1x1
pw.context:       Rectangle 1x1
pw.context:       Rectangle -1x-1
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000
pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
pw.context:       Fraction 60/1
pw.context:       Fraction 0/1
pw.context:       Fraction 60/1
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000
pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
pw.context:       Fraction 60/1
pw.context:       Fraction 0/1
pw.context:       Fraction 60/1
pw.context: Object: size 352, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
pw.context:     Id 2        (Spa:Enum:MediaType:video)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
pw.context:     Id 1        (Spa:Enum:MediaSubtype:raw)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
pw.context:     Id 8        (Spa:Enum:VideoFormat:BGRx)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:modifier (131074), flags 00000018
pw.context:     Choice: type Spa:Enum:Choice:Enum, flags 00000000 88 8
pw.context:       Long 144115188622605059
pw.context:       Long 144115188622605059
pw.context:       Long 144115188622588675
pw.context:       Long 144115188622392067
pw.context:       Long 144115188621122307
pw.context:       Long 144115188084250882
pw.context:       Long 144115188075858177
pw.context:       Long 0
pw.context:       Long 72057594037927935
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000
pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
pw.context:       Rectangle 1x1
pw.context:       Rectangle 1x1
pw.context:       Rectangle -1x-1
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000
pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
pw.context:       Fraction 60/1
pw.context:       Fraction 0/1
pw.context:       Fraction 60/1
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000
pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
pw.context:       Fraction 60/1
pw.context:       Fraction 0/1
pw.context:       Fraction 60/1
pw.context: Object: size 248, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
pw.context:     Id 2        (Spa:Enum:MediaType:video)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
pw.context:     Id 1        (Spa:Enum:MediaSubtype:raw)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
pw.context:     Id 8        (Spa:Enum:VideoFormat:BGRx)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000
pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
pw.context:       Rectangle 1x1
pw.context:       Rectangle 1x1
pw.context:       Rectangle -1x-1
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000
pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
pw.context:       Fraction 60/1
pw.context:       Fraction 0/1
pw.context:       Fraction 60/1
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000
pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
pw.context:       Fraction 60/1
pw.context:       Fraction 0/1
pw.context:       Fraction 60/1
pw.context: params Spa:Enum:ParamId:EnumFormat: 1:0 Invalid argument (output format (no more input formats))
pw.context: Object: size 184, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
pw.context:     Id 2        (Spa:Enum:MediaType:video)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
pw.context:     Id 1        (Spa:Enum:MediaSubtype:raw)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
pw.context:     Id 7        (Spa:Enum:VideoFormat:RGBx)
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000
pw.context:     Rectangle 2526x1368
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000
pw.context:     Fraction 0/1
pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000
pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
pw.context:       Fraction 60/1
pw.context:       Fraction 1/1
pw.context:       Fraction 60/1
pw.link: (37.0 -> 40.0) negotiating -> error (no more input formats)
```

(Copied from `journalctl --user --user-unit pipewire.service -f`)

I spotted the words "framerate" and "maxFramerate" in the error message, so I thought perhaps my 240hz monitor was the culprit. I reduced my framerate to 60, restarted xdg-desktop-portal-hyprland, xdg-desktop-portal and pipewire, but I still got the exact same error.

---

- `chromium 112.0.5615.165-1`
- `google-chrome 112.0.5615.165-1`
- `vivaldi 6.0.2979.15-1`
- `firefox 112.0.1-1`
- `hyprland 0.24.1-1`
- `xdg-desktop-portal 1.16.0-1`
- `xdg-desktop-portal-hyprland 0.3.0-1`
- `pipewire 1:0.3.69-2`
- `wireplumber 0.4.14-1`

**Comment by vaxerski** [comment]
one solution to this would be to stop using poo poo browsers.

**Comment by Hubro** [comment]
Hey now, Vivaldi is a pretty great browser! It's just based on a poo poo browser...

**Comment by vaxerski** [comment]
firefox: works
obs: works

cHrOmIuM:
works
doesnt work
fix pushed
works
doesnt work

**Comment by mordax7** [comment]
xdg-desktop-portal-wlr apparently fixed the problem in Sway.

**Comment by Hubro** [comment]
@mordax7 Do you have a link? I'm unable to find anything like this being resolved recently in xdpw :thinking:

**Comment by mordax7** [comment]
@Hubro I do not have a link. My work colleagues running Sway with xdg-desktop-portal-wlr 0.6 had the same problem with Chromium as xdg-desktop-portal-hyprland has. Apparently after the release 0.7 of `xdg-desktop-portal-wlr` Chromium started to work again. But again, this is only what has been told to me by one, two colleagues.

**Comment by vaxerski** [comment]
should work after c0e233955568fbea4e859336f6d3d14d51294d7c

**Comment by vaxerski** [comment]
idk, can you?

**Comment by vaxerski** [comment]
done

**Comment by mordax7** [comment]
@vaxerski Chromium still does not work for me.

**Comment by Zeioth** [comment]
> should work after [c0e2339](https://github.com/hyprwm/xdg-desktop-portal-hyprland/commit/c0e233955568fbea4e859336f6d3d14d51294d7c)

I've been able to make it work on chronium using xdg-desktop-portal-hyprland-git (AUR). Color needs to be setted to 8 bits 

    monitor = $screen1,3840x2160@60,0x0,1,bitdepth,8

10 bit is expected to not work correctly at the moment on xdg-desktop-portal-hyprland or in xdg-desktop-portal-wlr (sway)

![screenshot_2023-05-04_13-02-03_571483707](https://user-images.githubusercontent.com/3357792/236186526-3311bc3e-855f-4ec4-9638-26e7d995ec0d.png)

Proof. Also tested on Google Meet and Zoom (web version) and works as expected.

**Comment by rettetdemdativ** [comment]
> > should work after [c0e2339](https://github.com/hyprwm/xdg-desktop-portal-hyprland/commit/c0e233955568fbea4e859336f6d3d14d51294d7c)
> 
> I've been able to make it work on chronium using xdg-desktop-portal-hyprland-git (AUR). Color needs to be setted to 8 bits
> 
> ```
> monitor = $screen1,3840x2160@60,0x0,1,bitdepth,8
> ```
> 
> 10 bit is expected to not work correctly at the moment on xdg-desktop-portal-hyprland or in xdg-desktop-portal-wlr (sway)
> 
> ![screenshot_2023-05-04_13-02-03_571483707](https://user-images.githubusercontent.com/3357792/236186526-3311bc3e-855f-4ec4-9638-26e7d995ec0d.png)
> 
> Proof. Also tested on Google Meet and Zoom (web version) and works as expected.

This doesn't  seem to change anything for me, unfortunately.

**Comment by Zeioth** [comment]
You might need hyprland-git too. I'm on AMD, if that matters.

**Comment by rettetdemdativ** [comment]
For me, screensharing seems to work again in Electron-based applications and Firefox.

**Comment by jnsgruk** [comment]
Also seeing this on nixOS with latest hyprland/google-chrome as of today.

I can post the trace if useful?

**Comment by jnsgruk** [comment]
So a few more details:

Running hyprland and xdg-desktop-portal-hyprland from the nix flake.

`xdg-desktop-portal-hyprland-0.pre+date=2023-04-25_c0e2339`
`hyprland-0.25.0+date=2023-05-17_79b8576
`xdg-desktop-portal-1.16.0`
`google-chrome-113.0.5672.92`

Trace when I try to share a window:

```
May 18 09:04:30 loki xdg-desktop-portal-hyprland[569818]: warning: queue 0x1bb25f0 destroyed while proxies still attached:
May 18 09:04:30 loki xdg-desktop-portal-hyprland[569818]:   wl_display@1 still attached
May 18 09:04:30 loki wireplumber[2564]: <WpPortalPermissionStorePlugin:0x88d670> Failed to call Lookup: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for camera
May 18 09:04:30 loki pipewire[2563]: pw.context: params Spa:Enum:ParamId:EnumFormat: 0:0 Invalid argument (input format (no more input formats))
May 18 09:04:30 loki pipewire[2563]: pw.context: Object: size 336, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 2        (Spa:Enum:MediaType:video)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 1        (Spa:Enum:MediaSubtype:raw)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 12       (Spa:Enum:VideoFormat:BGRA)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:modifier (131074), flags 00000018
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Enum, flags 00000000 72 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 144115188085734146
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 144115188085734146
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 144115188084251394
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 144115188084250882
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 144115188075858177
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 0
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 72057594037927935
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Rectangle 1x1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Rectangle 1x1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Rectangle -1x-1
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 0/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 0/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context: Object: size 248, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 2        (Spa:Enum:MediaType:video)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 1        (Spa:Enum:MediaSubtype:raw)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 12       (Spa:Enum:VideoFormat:BGRA)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Rectangle 1x1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Rectangle 1x1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Rectangle -1x-1
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000
May 18 09:04:30 loki hyprland[4166]: [4155:569848:0518/090430.072195:ERROR:shared_screencast_stream.cc(241)] PipeWire stream state error: no more input formats
May 18 09:04:30 loki hyprland[4166]: [4155:569848:0518/090430.072208:ERROR:shared_screencast_stream.cc(204)] PipeWire remote error: no more input formats
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 0/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 0/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context: Object: size 336, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 2        (Spa:Enum:MediaType:video)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 1        (Spa:Enum:MediaSubtype:raw)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 11       (Spa:Enum:VideoFormat:RGBA)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:modifier (131074), flags 00000018
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Enum, flags 00000000 72 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 144115188085734146
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 144115188085734146
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 144115188084251394
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 144115188084250882
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 144115188075858177
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 0
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 72057594037927935
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Rectangle 1x1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Rectangle 1x1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Rectangle -1x-1
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 0/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 0/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context: Object: size 248, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 2        (Spa:Enum:MediaType:video)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 1        (Spa:Enum:MediaSubtype:raw)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 11       (Spa:Enum:VideoFormat:RGBA)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Rectangle 1x1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Rectangle 1x1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Rectangle -1x-1
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 0/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 0/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context: Object: size 336, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 2        (Spa:Enum:MediaType:video)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 1        (Spa:Enum:MediaSubtype:raw)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 8        (Spa:Enum:VideoFormat:BGRx)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:modifier (131074), flags 00000018
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Enum, flags 00000000 72 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 144115188085734146
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 144115188085734146
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 144115188084251394
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 144115188084250882
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 144115188075858177
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 0
May 18 09:04:30 loki pipewire[2563]: pw.context:       Long 72057594037927935
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Rectangle 1x1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Rectangle 1x1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Rectangle -1x-1
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 0/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 0/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context: Object: size 248, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 2        (Spa:Enum:MediaType:video)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 1        (Spa:Enum:MediaSubtype:raw)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 8        (Spa:Enum:VideoFormat:BGRx)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Rectangle 1x1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Rectangle 1x1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Rectangle -1x-1
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 0/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 0/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context: params Spa:Enum:ParamId:EnumFormat: 1:0 Invalid argument (output format (no more input formats))
May 18 09:04:30 loki pipewire[2563]: pw.context: Object: size 184, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 2        (Spa:Enum:MediaType:video)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 1        (Spa:Enum:MediaSubtype:raw)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Id 7        (Spa:Enum:VideoFormat:RGBx)
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Rectangle 3824x2102
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Fraction 0/1
May 18 09:04:30 loki pipewire[2563]: pw.context:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000
May 18 09:04:30 loki pipewire[2563]: pw.context:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 1/1
May 18 09:04:30 loki pipewire[2563]: pw.context:       Fraction 60/1
May 18 09:04:30 loki pipewire[2563]: pw.link: (85.0 -> 94.0) negotiating -> error (no more input formats)
```

**Comment by dsod** [comment]
Started working today after updating the system. Looks like a upstream issue have been resolved.

**Comment by impankratov** [comment]
@dsod Hi, can you specify updated packages versions? Like what versions of chrome, xdg-desktop-portal-hyprland etc. are you using right now, so others can test it too)

**Comment by jnsgruk** [comment]
Hmm I'm running similar versions on nixOS and still seeing the same problem sadly

**Comment by ppenguin** [comment]
@jnsgruk 

Have you solved this?

I'm also on `NixOS`, since about a week I have the same issue for both Firefox and Chrome/Brave, while a few months ago it appeared only on Chrome and Firefox worked. It started around the same time when I went from Hyprland `0.27.2 -> 0.28.0`, but reverting (via `flake` inputs) didn't make a difference.

I'm getting  (Chrome)
```
[154218:154218:0809/141155.388860:ERROR:feature_processor_state.cc(39)] Processing error occured: model WebAppInstallationPromo failed with UkmEngineDisabled, message:
[154218:155257:0809/141224.464920:ERROR:shared_screencast_stream.cc(241)] PipeWire stream state error: no more input formats
[154218:155257:0809/141224.464932:ERROR:shared_screencast_stream.cc(204)] PipeWire remote error: no more input formats
```

and a similar `pipewire` output as you posted above.

**Comment by jnsgruk** [comment]
Afraid not -- still broken here.

**Comment by vaxerski** [comment]
closing due to the v1.0 rewrite
